# Generated by Django 4.2.5 on 2026-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_amount_paid_invoice_balance_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expences',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
