# Generated by Django 4.2.5 on 2026-02-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_expences_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
