# Generated by Django 4.2.5 on 2025-11-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_customer_customer_email_customer_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_points',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Membership', 'Membership')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
