# Generated by Django 4.2.5 on 2025-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_customer_customer_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='services_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='services_duration',
            field=models.IntegerField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='services_image',
            field=models.ImageField(blank=True, null=True, upload_to='services_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='services_price',
            field=models.IntegerField(default=1, max_length=255),
        ),
    ]
