# Generated by Django 4.2.5 on 2026-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_product_membership_price_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=1, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
            ],
        ),
    ]
