# Generated by Django 4.2.5 on 2026-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_expences'),
    ]

    operations = [
        migrations.AddField(
            model_name='expences',
            name='expence_is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
