# Generated by Django 4.2.5 on 2026-01-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_expences_expence_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1, max_length=255)),
                ('Price', models.IntegerField(default=1, max_length=255)),
                ('expence_is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
