# Generated by Django 4.2.5 on 2026-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
